import { studioZh } from "./studio.zh"

export const coursewareCreateZh = {
    studio: studioZh,
    previewLoading: '课件预览加载中...',
    preview: {
      title: '课件预览',
      backToList: '返回列表',
      download: '下载课件',
      iframeTitle: '课件预览'
    },
    series: {
      title: '系列课件',
      count: '已完成 {count} 个子课件，可按顺序查看课程内容。',
      backToGeneration: '返回生成页面',
      viewResults: '查看完整课件',
      coursewareCount: '个子课件',
      part: '第 {index}/{count} 部分',
      estimatedDuration: '预计 {minutes} 分钟',
      download: '下载',
      preview: '预览课件',
      empty: '暂无可预览结果'
    },
    title: 'AI 智能课件生成',
    subtitle: '从业务经验到可学习的课程，一起梳理、打磨与制作',
    steps: {
      upload: '上传资料',
      generating: 'AI生成中',
      review: '审核与发布'
    },
    uploadTitle: '拖拽 PDF、Word 或 PPT 文件至此或点击上传',
    uploadHint: '支持 PDF、Word、PPT，每个文件不超过 {size}MB',
    emptyUpload: '暂无上传资料，可直接使用下方提示词生成',
    promptOnlyHint: '没有上传资料时，提示词将作为主要内容来源，并通过联网搜索补充和核验信息。',
    scriptModeRequiresFiles: '“保留原始课件”需要至少上传一个课件文件。',
    courseTitle: '课件标题',
    courseTitlePlaceholder: '单文件会自动带出文件名，多文件请手动填写',
    catalogLabel: '品牌与产品分类（可选）',
    catalog: {
      manage: '查看与添加分类',
      manageTitle: '品牌与产品分类',
      manageHint: '品牌 / 品类 / 系列 / 产品',
      manageNotice: '这里只能查看和新增。修改或删除品牌、品类与系列请前往类目管理，产品请前往产品管理。',
      empty: '暂无分类，可先添加品牌',
      addBrand: '添加品牌',
      category: '新增品类',
      series: '新增系列',
      product: '新增产品',
      addPlaceholder: '输入名称',
      addSuccess: '已添加，下拉选项已更新'
    },
    catalogPlaceholder: '搜索并选择产品类目或产品',
    catalogSummary: '已选择 {brands} 个品牌、{categories} 个类目、{products} 个产品',
    additionalInstruction: '附加生成指令（可选）',
    additionalInstructionPlaceholder:
      '例如：重点突出我们产品的吸收速度，并生成与 Lbrand 的对比页。主语言使用本土化印尼语。',
    generateHomework: '同步生成十道题',
    generateHomeworkTip: '课件生成完成后，将根据课件内容同步生成 10 道课后附加题。',
    settings: {
      enableImageGeneration: 'AI生图',
      enableImageGenerationTip: 'AI 会根据课件内容自动生成合适的配图。',
      outlineEnhancement: '拆分优化',
      outlineEnhancementTip: '根据上传资料和用户需求启动智能拆分功能'
    },
    narratorRole: '讲解角色：',
    narratorPlaceholder: '请选择讲解角色',
    unknownGender: '未知',
    narratorGender: {
      male: '男',
      female: '女'
    },
    generationLanguage: '课件语言',
    generationLanguages: {
      cn: '中文',
      en: '英文',
      id: '印尼语'
    },
    clarificationTitle: '补充生成要求',
    clarificationDescription: '请完成以下必答项。已预选推荐项，可按需选择其他选项。',
    recommendedOption: '推荐',
    customAnswer: '自定义',
    customAnswerPlaceholder: '请输入自定义回答',
    answerPlaceholder: '请输入回答',
    submitAnswers: '提交回答',
    confirmationTitle: '确认生成摘要',
    confirmationDescription:
      '请确认系统整理后的要求摘要，确认后继续生成；拒绝后返回创建页修改原始要求。',
    summaryTitle: '标题',
    summaryAudience: '受众',
    summaryObjective: '目标',
    summaryLanguage: '语言',
    summaryDuration: '时长',
    durationMinutes: '{minutes} 分钟',
    summaryScope: '范围',
    summaryMustInclude: '必须包含：',
    summaryOptional: '可选内容：',
    summaryMustExclude: '明确排除：',
    summaryAssumptions: '假设',
    summaryListSeparator: '、',
    summaryReject: '拒绝',
    summaryConfirmContinue: '确认并继续',
    waitingAnswersTitle: '等待补充生成要求',
    waitingAnswersDescription: '请完成所有必答项后提交回答。',
    waitingConfirmationTitle: '等待确认生成摘要',
    waitingConfirmationDescription: '请确认或拒绝当前摘要。',
    reviewingOutlineTitle: 'AI 正在审查完整大纲...',
    splittingOutlineTitle: 'AI 正在拆分大纲...',
    generatingChildrenTitle: 'AI 正在生成子课件...',
    answerRequired: '请完成问题：{question}',
    customAnswerRequired: '请填写问题“{question}”的自定义回答',
    submitAnswersFailed: '提交回答失败，请稍后重试',
    submitConfirmationFailed: '提交确认失败，请稍后重试',
    modeAi: '使用AI智能生成课件',
    modeScript: '保留原始课件，仅生成讲解',
    startButton: '开始智能生成',
    uploadingButton: '文件上传中...',
    pauseUpload: '暂停',
    resumeUpload: '继续',
    retryUpload: '重试',
    recoverableUploadsTitle: '可恢复的上传',
    recoverableUploadsDesc: '选择原始本地文件后，可继续未完成的上传。',
    resumeTaskMeta: '已上传 {progress}% · 更新于 {time}',
    continueUpload: '继续上传',
    discardUpload: '丢弃',
    resumeFileMismatch: '请选择原始文件继续上传，文件名、大小或修改时间不匹配。',
    resumeTaskExpired: '部分未完成上传已过期，请重新上传文件。',
    discardUploadLocalOnly: '远程会话不可用，已移除本地恢复记录。',
    resumeSessionUnavailable: '上传会话已不可恢复，请重新上传文件。',
    generatingTitle: 'AI 正在深度解析文档...',
    homeworkGeneratingTitle: '课后10道题生成中...',
    homeworkGeneratingDesc: '课件已完成，正在生成并回填10道课后题，完成后统一展示。',
    queuedTitle: '课件排队生成中...',
    generatingDesc: '系统正在提取知识点并生成对应的数字人讲解脚本，这可能需要 1-2 分钟。',
    leaveHint: '⚡ 您可以离开此页面处理其他任务，生成完成后我们将通知您。',
    progressLabel: '正在生成{language}课件及逐字稿...',
    workbench: {
      consoleTitle: '智能体执行',
      artifactsTitle: '生成产物',
      artifactsHint: '随生成进度实时出现',
      artifactsLiveHint: '正在实时更新',
      artifactsEmpty: '智能体完成需求确认后，大纲与子课件会出现在这里',
      activityTitle: '执行记录',
      activityEmpty: '等待智能体开始工作',
      untitledCourseware: '未命名课件',
      inProgress: '进行中',
      elapsed: '已运行 {time}',
      milestone: {
        parts: '子课件交付',
        partsPlain: '{completed}/{total} 完成',
        partsWithFailure: '{completed}/{total} 完成，{failed} 个失败'
      },
      stages: {
        clarify: '需求澄清',
        outline: '大纲生成',
        split: '拆分优化',
        children: '子课件生成',
        done: '完成'
      },
      activity: {
        prompt_enhancement_started: '开始理解你的需求',
        requirement_questions_presented: '向你确认关键决策',
        requirement_confirmation_presented: '等待你确认方案',
        user_answers_received: '已收到你的选择',
        requirement_confirmed: '方案已确认',
        prompt_enhancement_completed: '需求规格已确定',
        outline_review_started: '正在生成课程大纲',
        outline_review_completed: '课程大纲已生成',
        outline_split: '正在拆分系列课件',
        parts_selection_presented: '请选择要生成的子课件',
        parts_selected: '已确认子课件范围',
        child_created: '创建子课件任务',
        child_started: '开始生成子课件',
        child_retry: '重试子课件',
        child_succeeded: '子课件生成完成',
        child_failed: '子课件生成失败',
        job_succeeded: '全部生成完成',
        job_failed: '生成失败'
      },
      spec: {
        title: '需求规格书',
        audience: '目标学员',
        language: '课件语言',
        duration: '预计时长',
        tone: '表达风格',
        design: '视觉设计契约',
        typography: '字体',
        layout: '版式',
        imagery: '图像处理',
        mood: '氛围',
        minutes: '{minutes} 分钟'
      },
      research: {
        title: '资料研究',
        queries: '检索方向',
        conclusions: '关键结论',
        sources: '参考来源'
      },
      outline: {
        title: '大纲与拆分',
        parts: '个子课件',
        pendingPart: '第 {index} 部分（待拆分）'
      },
      series: {
        title: '子课件进度',
        part: '第 {index} 部分'
      }
    },
    questions: {
      title: '补充生成要求',
      description: '请为每个问题选择一个选项；全部完成后才能继续生成。',
      sourcePreparationPending:
        '材料正在后台解析。你可以先提交回答；系统会在材料解析完成后继续生成。',
      recommended: '推荐',
      noteLabel: '补充备注（可选）',
      notePlaceholder: '如有更具体的约束，请写在这里；备注优先于本题选项的泛化描述。',
      noOptions: '当前问题没有可选项，无法继续生成。',
      customOption: '自己描述',
      customPlaceholder: '用一句话描述你的期望，例如：米白背景、单一强调色、页面留白更多',
      cancel: '取消本轮生成',
      submit: '提交回答',
      required: '请完成问题：{question}',
      invalidOption: '请选择问题“{question}”中的有效选项',
      waitingDescription: '请完成所有必答项后提交 answer。',
      waitingWithSourceDescription: '请完成所有必答项；材料解析完成后系统会继续生成。'
    },
    parts: {
      title: '选择要生成的子课件',
      description: '这份课件已拆分为 {count} 个子课件。取消勾选不需要的部分，只生成你选中的内容。',
      untitled: '第 {index} 部分',
      meta: '第 {index}/{count} 部分 · 约 {minutes} 分钟 · {pages} 页',
      hint: '未勾选的子课件不会生成，也不会占用生成时间。',
      emptySelection: '请至少勾选一个子课件'
    },
    confirmation: {
      title: '确认生成摘要',
      description: '请确认系统整理后的要求摘要，确认后继续生成；拒绝后返回创建页修改原始要求。',
      fields: {
        title: '标题',
        audience: '受众',
        objective: '目标',
        language: '语言',
        duration: '时长',
        scope: '范围',
        mustInclude: '必须包含',
        optional: '可选内容',
        mustExclude: '明确排除',
        assumptions: '假设'
      },
      reject: '拒绝',
      confirm: '确认并继续',
      durationMinutes: '{minutes} 分钟'
    },
    status: {
      waitingForUser: '等待补充生成要求',
      waitingForConfirmation: '等待确认生成摘要',
      reviewingOutline: 'AI 正在审查完整大纲...',
      splittingOutline: 'AI 正在拆分大纲...',
      generatingChildren: 'AI 正在生成子课件...',
      reviewingOutlineDescription: 'AI 正在梳理完整大纲并优化课程结构。',
      splittingOutlineDescription: 'AI 正在根据资料与需求判断是否需要拆分课件。',
      generatingChildrenDescription: 'AI 正在依次生成各个子课件。',
      seriesProgress: '子课件进度',
      completedCount: '已完成 {completed}/{total}',
      completed: '已完成',
      failed: '失败',
      cancelled: '已取消',
      generating: '生成中',
      queued: '排队中',
      running: '运行中',
      processing: '处理中'
    },
    failedTitle: '课件生成失败',
    failedDesc: '生成任务未完成，请返回创建页检查资料后重新开始。',
    retryHomeworkButton: '重试附加题',
    retryHomeworkHint: '课件已生成成功，仅附加题生成失败；重试只重新生成附加题，不会重新生成课件。',
    retryHomeworkConfirm: '将为该课件重新生成并自动关联附加题，任务进度可在顶部站内信中查看。',
    retryHomeworkStart: '开始生成',
    retryHomeworkSubmitted: '附加题生成任务已提交，请在顶部站内信查看进度',
    cancelledTitle: '课件生成已取消',
    cancelledDesc: '生成任务已取消，可返回创建页重新发起生成。',
    backToCreate: '返回重新创建',
    cancelAndBackToUpload: '取消生成并返回上传',
    publishButton: '发布课件',
    publishedButton: '已发布',
    publishSuccess: '发布成功',
    publishFailed: '发布失败，请稍后重试',
    unsupportedFile: '仅支持上传 PDF、Word 或 PPT 文件',
    uploadSingleFileOnly: '参考资料仅支持一个文件，请先移除已上传的文件',
    fileTooLarge: '单个文件大小不能超过 {size}MB',
    directModeUnsupportedFile: '当前文件不支持保留原始课件模式：{names}',
    uploadFailed: '文件 {name} 上传失败',
    uploadFailedRetry: '文件 {name} 上传失败，请重试',
    uploadOffline: '网络连接已断开，文件 {name} 上传失败，请恢复网络后重试',
    uploadTimeout: '文件 {name} 上传超时，请检查网络后重试',
    uploadNetworkError: '文件 {name} 网络请求失败，请检查网络或上传服务连接后重试',
    uploadAuthorizationExpired: '文件 {name} 的上传授权无效或已过期，请重试',
    uploadServerError: '上传服务暂时不可用，文件 {name} 上传失败，请稍后重试',
    uploadSuccess: '文件 {name} 上传成功',
    waitUploading: '文件上传未完成，请稍后再开始生成',
    needPromptOrUpload: '请上传 PDF、Word、PPT 资料，或填写生成提示词',
    needTitle: '请先填写课件标题',
    needTitleForMultiple: '多个文件时请先填写课件标题',
    waitingIntegration: '外部生成服务待接入，后台适配器暂未启用',
    cancelGenerationFailed: '取消生成失败，请稍后重试',
    microphonePermissionTimeout: 'App 麦克风权限申请超时，请重试或检查 App 权限桥接'
  }
