export const studioZh = {
  addFiles: '继续添加文件',
  connectionInterrupted: '暂未获取最新进度，正在自动重试。当前内容已保留，无需重新生成。',
  courseGoals: '课程目标与范围',
  courseSummary: '课程摘要',
  editSection: '编辑',
  finishEditing: '完成编辑',
  sectionPurpose: '学习目标与讲解安排',
  sectionTitle: '章节标题',
  sectionCount: '共 {count} 个章节',
  noneAnswer: 'None · 我自己填写',
  generatedPages: '页面制作',
  completedPages: '已完成 {completed} / {total} 页',
  partStates: {
    QUEUED: '等待制作',
    RUNNING: '制作中',
    SUCCEEDED: '已完成',
    FAILED: '制作失败',
    CANCELED: '已停止'
  },
  sourceSummary: '已整理的资料',
  previewPage: '只读预览',
  previewLoading: '正在加载实际页面…',
  previewUnavailable: '页面暂不可用，请关闭后重试。',
  mediaPending: '页面内容已完成，图片、视频或语音仍在制作中。',
  quizCardTitle: '课后练习',
  quizCardStatus: '生成中',
  quizCardHint: '本子课件的其他页面完成后，将立即生成并追加课后练习。',
  syncingHomework: '正在同步课后题',
  queuedHomework: '等待同步课后题',
  autoRetry: '已自动重试 {count} 次',
  pageStates: {
    waiting: '等待制作',
    generating: '制作中',
    retrying: '自动重试中',
    completed: '页面已完成',
    failed: '制作失败'
  },
  phases: {
    sources: '正在处理资料',
    interview: '补充课程信息',
    plan: '正在整理课程大纲',
    outline: '正在细化页面结构',
    pages: '正在逐页制作',
    generating_scenes: '正在生成页面',
    generating_media: '正在生成媒体',
    generating_tts: '正在生成语音',
    persisting: '正在保存课件',
    queued: '等待开始',
    finalizing: '正在整合课件',
    completed: '课件已完成',
    failed: '制作失败',
    canceled: '已取消'
  },
  phaseHints: {
    sources: '读取资料内容，为课程方案提供依据。',
    interview: '补充必要信息后继续。',
    plan: '整理课程结构、章节目标和内容要点，完成后可直接修改并确认。',
    outline: '正在根据课程规划生成逐页大纲，完成后请确认；确认前不会制作页面。',
    pages: '完成一页即可预览；列表按已确认的大纲排序。',
    generating_scenes: '正在逐页生成内容，已完成的页面会保留在右侧。',
    generating_media: '页面已生成，正在处理图片和视频。',
    generating_tts: '页面已生成，正在处理语音。',
    persisting: '正在保存页面和课件数据。',
    queued: '任务已排队，马上开始。',
    finalizing: '页面内容已制作，正在整合媒体、保存课件和同步练习。',
    completed: '全部制作已完成。',
    failed: '本次制作未完成。',
    canceled: '本次制作已停止。'
  },

  processStepsTitle: '课程共创流程',
  title: '课程共创',
  understand: '梳理目标',
  coCreate: '课程规划',
  review: '确认大纲',
  produce: '生成课件',
  progress: '制作进度',
  saved: '进度已保存',
  connecting: '正在建立课程',
  workspace: '制作工作区',
  conversation: '与 AI 共创',
  draft: '课程草稿',
  coach: '课程助手',
  interviewIntro: '我们先把关键内容聊清楚。我会把你的回答整理在右侧，再一起确认课程大纲。',
  recommended: '建议',
  ownAnswer: '也可以说说你的想法',
  yourExperience: '你的经验',
  answerPlaceholder: '像和同事聊天一样，说说当时的情况、你的做法和结果。没有案例也可以告诉我。',
  addDetail: '补充一个细节（可选）',
  detailPlaceholder: '例如：要突出的方法、真实案例，或不希望涉及的内容。',
  outlineReady: '课程大纲已经准备好了',
  briefReady: '我们把课程方向理清了',
  outlineReadyHint:
    '右侧已整理完整的课程结构、各章节目标和内容要点。可以直接修改，确认后按这份大纲逐页制作课件。',
  briefReadyHint:
    '右侧是可编辑的课程规划。调整章节目标和内容后，生成正式逐页大纲；你确认逐页大纲后才会开始制作课件。',
  reviewDraft: '查看并修改草稿',
  outlineCheckpoint: '确认后会沿用这份大纲制作课件，保留你在这里的修改。',
  briefCheckpoint: '下一步先生成大纲，你还可以逐页调整，再开始制作课件。',
  retryHomework: '重试生成练习',
  understanding: '正在理解你的课程目标',
  understandingHint: '正在整理输入内容，寻找最值得进一步聊清楚的问题。',
  readingSources: '同时在阅读你上传的资料，已提供的信息不会再让你重复填写。',
  productionProgress: '课件制作进度',
  leaveHint:
    '完整课件制作可能需要较长时间。你可以离开此页去做其他事，稍后从任务历史返回查看进度和预览，无需一直等待。',
  back: '返回创建',
  endSession: '结束本次制作',
  saving: '正在保存',
  continue: '继续梳理',
  generateCourse: '确认大纲，生成课件',
  generateOutline: '生成课程大纲',
  workingHint: '完成后会在这里更新',
  outline: '课程大纲',
  editable: '可直接修改',
  fromConversation: '根据对话整理',
  pageCount: '共 {count} 页，展开可查看内容',
  types: { slide: '讲解页', quiz: '随堂练习', interactive: '互动活动', pbl: '情境任务' },
  pageTitle: '页面标题',
  pagePurpose: '这一页要讲清什么',
  keyPoints: '内容要点（每行一条）',
  editBriefHint: '先确定教什么、教给谁。措辞和内容都可以直接修改。',
  courseTitle: '课程主题',
  audience: '面向谁',
  objective: '学完能够做到什么',
  scope: '核心内容（每行一条）',
  assumptions: '尚待确认的假设',
  experience: '你的真实经验',
  keySteps: '提炼出的关键动作',
  boundaries: '适用边界',
  emptyTitle: '你的经验，会在这里成为课程',
  emptyHint: '随着对话推进，已理解的目标、案例和方法会逐步整理在这里。',
  emptyGoal: '明确学员要解决的问题',
  emptyExperience: '提炼经验中的关键动作',
  emptyStructure: '形成可以逐页调整的大纲',
  producing: '正在制作的课件',
  confirmationHint: '确认前不会开始制作页面',
  backToChat: '返回确认',
  selectPart: '请至少选择一个要生成的部分。',
  completePages: '请补全每个章节的标题、讲解安排和内容要点。',
  completeBrief: '请补充课程主题、目标学员和学习目标。',
  entryTitle: '把你的经验，变成一堂好课',
  entryHint: '说说你想教什么。课程助手会帮你梳理关键内容，再一起打磨大纲。',
  promptLabel: '这次想做一堂什么课？',
  promptPlaceholder: '例如：给门店新人做一堂客户异议处理课，重点是客户说“太贵了”时怎么回应。',
  courseType: '这堂课更侧重',
  auto: '帮我判断',
  experienceType: '分享经验',
  operationType: '教会操作',
  knowledgeType: '讲清方法',
  start: '开始共创课程',
  filesOptional: '添加参考资料（可选）',
  autoConfirm: '直接完成（自动继续全流程）',
  settings: '手动选择',
  settingsHint: '打开后手动选择生成参数，关闭则通过问答确认',
  example1: '客户说“太贵了”，如何回应',
  example2: '让新人掌握产品演示流程',
  example3: '把一次成功成交复盘成课',
  interviewRound: '第 {count} 轮',
  understoodContent: '已理解的内容',
  insightsCount: '{count} 项内容',
  coachRole: '课程共创助手',
  coachStatus: '与你一起梳理课程',
  shortcutSend: '按 ⌘/Ctrl + Enter 发送',
  rationaleLabel: '为什么问',
  justUpdated: '刚更新',
  expandAll: '展开全部',
  collapseAll: '收起全部',
  inspirationLabel: '灵感参考',
  stepExtract: '萃取步骤',
  stepStage1: '梳理经验',
  stepStage2: '提炼干货',
  stepStage3: '生成大纲',
  coCreationPill: 'AI 课程共创工作区',
  roadmapStep1: '聊聊你的经验',
  roadmapStep1Desc: '结构化提炼一线真实业务经验',
  roadmapStep2: '一起打磨大纲',
  roadmapStep2Desc: '提炼核心要点，自由调整教学逻辑',
  roadmapStep3: '制作可学习的课程',
  roadmapStep3Desc: '将确认的内容制作成课件',
  canvasLiveBadge: '实时沉淀',
  canvasBlueprintTitle: '一堂好课的萃取结构',
  emptyCard1Title: '目标学员与业务痛点',
  emptyCard1Desc: '明确谁在什么实际业务场景下需要掌握这门技能',
  emptyCard2Title: '实战动作与应对策略',
  emptyCard2Desc: '从真实经历中提炼解决问题的具体动作与标准',
  emptyCard3Title: '逐页讲解与互动设计',
  emptyCard3Desc: '将知识沉淀为层层递进的逐页大纲与配套习题',
  reviewOutlineSummary: '大纲包含 {parts} 个部分，共 {pages} 页课件',
  slideCountBadge: '共 {count} 页'
}
